database:
  image: mysql:5
  rootPassword: rootpw
  userName: drupal
  userPassword: changeme
  tinyConfiguration: ""
  memcacheKnownEnabled: false
  persistence:
    storageClass: ""

drupal:
  image: drupal:8
  persistence:
    storageClass: ""

memcached:
  image: memcached:1.5-alpine
  memory: 64

imageCredentials: ~
  # registry: server
  # username: username
  # password: password

scheduler: ""
persistence:
  storageClass: ""

dev:
  path: ""

ingress:
  host: ~
  hosts: []
  tls:
    enabled: false
    certManager:
      clusterIssuer: ""
      issuer: ""
  modsecurity:
    enabled: false
    owasp: false
    whitelist: ""
    adminWhitelist: ""