{{- if (or .Values.ingress.host .Values.ingress.hosts) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drupal
  annotations: {}
spec:
  rules:
{{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: drupal
            servicePort: 80
{{ end }}
{{ range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          backend:
            serviceName: drupal
            servicePort: 80
{{ end }}
{{ end -}}