{{- if .Values.ingress.host }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drupal
  annotations: {}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: drupal
            servicePort: 80
{{ end -}}