apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-data
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  {{- $storageClass := default .Values.persistence.storageClass .Values.drupal.persistence.storageClass }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 5Gi