{{- if .Release.IsInstall }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ default .Values.persistence.storageClass .Values.drupal.persistence.storageClass }}
  resources:
    requests:
      storage: 5Gi
{{- end }}