{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: drupal-image-pull-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .Values.imageCredentials }}"
{{ end -}}
