apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: {{ .Values.memcached.image }}
          args:
            - --memory-limit={{ .Values.memcached.memory }}
          imagePullPolicy: Always
          ports:
            - containerPort: 11211
          resources:
{{- if .Values.memcached.resources }}
{{ .Values.memcached.resources | toYaml | indent 12 }}
{{- else }}
            requests:
              cpu: 10m
              memory: {{ .Values.memcached.memory }}M
            limits:
              memory: {{ add .Values.memcached.memory 10 }}M
{{- end }}