apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ default .Values.persistence.storageClass .Values.database.persistence.storageClass }}
  resources:
    requests:
      storage: 5Gi
