name: Release

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run the build script
      run: ./build.sh
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: build
      - run: find . -type f