name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: build
      - run: find . -type f